server {
    listen 80;
    server_name digitalbharatads.com;

    root digitalbharatads.com/sustrack/client/v2;

    location /sustrack/client/v2/ {
        try_files $uri $uri/ /sustrack/client/v2/index.html;
    }

    location / {
        try_files $uri $uri/ /sustrack/client/v2/index.html =404;
    }
}
